### ISSUE TITLE
Question:Is it possible to call external cli apps or run commands and fetch the results in game.

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [Spoonail-Iroiro/maginai#61]
If this is possible then we can try generate the npc/character's response with LLM(AI).
Of course,it will not be easy to make the plugin and making sure it is bug free.

ただ、その可能性お考えるだけです。

**Comment by Spoonail-Iroiro** [comment]
Interesting idea! 
However, unfortunately, this mod loader and its mods currently can't call external apps/commands or send requests to the web. 
The reason is that they only work on the local JavaScript part of the game (still it's most parts of the game). 
Due to the security function of the browser in the game app, local javascript code can't access local files other than javascript or image files, or send web requests. 

To bypass these restrictions, it would be necessary to mod the C# part of the game. 
(Actually, the javascript part of the game transfer processes which is prohibited by the security, such as web requests to the contents uploader, to the C# part of the game.) 
However, this would require writing new mod loader code for C#, which would take a time.

**Comment by hgftrdw45ud67is8o89** [comment]
i see huge thanks for information.I will close this issue then.^_^

It seems like a huge cost in development so i guess should nuke this idea, I don't think there's even a webview mod libraries.lmao.
